var team = [{
    "firstName": "Darran",
    "lastName": "Darran",
    "position": "WR",
    "number": 3,
    "image": "sticker.png",
},{
    "firstName": "Sebastian",
    "lastName": "Ritter",
    "position": "DB",
    "number": 4,
    "image": "sticker.png",
},{
    "firstName": "Marcel",
    "lastName": "Zintl",
    "position": "WR",
    "number": 7,
    "image": "sticker.png",
},{
    "firstName": "Jonas",
    "lastName": "Wienken",
    "position": "LB",
    "number": 9,
    "image": "sticker.png",
},{
    "firstName": "Janis",
    "lastName": "Stummer",
    "position": "WR",
    "number": 10,
    "image": "sticker.png",
},{
    "firstName": "Tobias",
    "lastName": "Neubauer",
    "position": "WR",
    "number": 11,
    "image": "sticker.png",
},{
    "firstName": "Florian",
    "lastName": "Eichhorn",
    "position": "WR",
    "number": 13,
    "image": "sticker.png",
},{
    "firstName": "Tobias",
    "lastName": "Fricke",
    "position": "WR",
    "number": 14,
    "image": "sticker.png",
},{
    "firstName": "Florian",
    "lastName": "Cosack",
    "position": "QB",
    "number": 15,
    "image": "sticker.png",
},{
    "firstName": "Benjamin",
    "lastName": "Geißhardt",
    "position": "RB",
    "number": 21,
    "image": "sticker.png",
},{
    "firstName": "Kevin",
    "lastName": "Thomas",
    "position": "DB",
    "number": 23,
    "image": "sticker.png",
},{
    "firstName": "Manuel",
    "lastName": "Mönch",
    "position": "LB",
    "number": 25,
    "image": "sticker.png",
},{
    "firstName": "Philipp",
    "lastName": "Priesner",
    "position": "LB",
    "number": 29,
    "image": "sticker.png",
},{
    "firstName": "Sven",
    "lastName": "Weschenfelder",
    "position": "DB",
    "number": 30,
    "image": "sticker.png",
},{
    "firstName": "Martin",
    "lastName": "Sünkel",
    "position": "WR",
    "number": 31,
    "image": "sticker.png",
},{
    "firstName": "Nico",
    "lastName": "Götz",
    "position": "RB",
    "number": 32,
    "image": "sticker.png",
},{
    "firstName": "Nils",
    "lastName": "Becker",
    "position": "LB",
    "number": 48,
    "image": "sticker.png",
},{
    "firstName": "Helmut",
    "lastName": "Krüger",
    "position": "",
    "number": 52,
    "image": "sticker.png",
},{
    "firstName": "Marcel",
    "lastName": "Amthor",
    "position": "C",
    "number": 53,
    "image": "sticker.png",
},{
    "firstName": "Michael",
    "lastName": "Schnetter",
    "position": "LB",
    "number": 54,
    "image": "sticker.png",
},{
    "firstName": "Martin",
    "lastName": "Jahn",
    "position": "G",
    "number": 55,
"image": "sticker.png",
},{
    "firstName": "Daniel",
    "lastName": "Kaufmann",
    "position": "DE",
    "number": 2,
    "image": "sticker.png",
},{
    "firstName": "Bastian",
    "lastName": "Meyer",
    "position": "DT",
    "number": 60,
    "image": "sticker.png",
},{
    "firstName": "Lukas",
    "lastName": "Priesner",
    "position": "DE",
    "number": 63,
    "image": "sticker.png",
},{
    "firstName": "Luca",
    "lastName": "Leutheuser",
    "position": "T",
    "number": 67,
    "image": "sticker.png",
},{
    "firstName": "Paul",
    "lastName": "Jakob",
    "position": "DE",
    "number": 72,
    "image": "sticker.png",
},{
    "firstName": "Johannes",
    "lastName": "Müller",
    "position": "T",
    "number": 73,
    "image": "sticker.png",
},{
    "firstName": "Pascal",
    "lastName": "Carl",
    "position": "",
    "number": 75,
    "image": "sticker.png",
},{
    "firstName": "Sebastian",
    "lastName": "Simon",
    "position": "G",
    "number": 76,
    "image": "sticker.png",
},{
    "firstName": "Julian",
    "lastName": "Langbein",
    "position": "G",
    "number": 77,
    "image": "sticker.png",
},{
    "firstName": "Kay",
    "lastName": "Niekut",
    "position": "G",
    "number": 78,
    "image": "sticker.png",
},{
    "firstName": "Alexander",
    "lastName": "Franz",
    "position": "",
    "number": 79,
    "image": "sticker.png",
},{
    "firstName": "Christian",
    "lastName": "Faber",
    "position": "DB",
    "number": 80,
    "image": "sticker.png",
},{
    "firstName": "Andreas",
    "lastName": "Merz",
    "position": "TE",
    "number": 84,
    "image": "sticker.png",
},{
    "firstName": "Luis",
    "lastName": "Eichorn",
    "position": "TE",
    "number": 86,
    "image": "sticker.png",
},{
    "firstName": "Leroy",
    "lastName": "Walter",
    "position": "DB",
    "number": 88,
    "image": "sticker.png",
},{
    "firstName": "Philipp",
    "lastName": "Koch",
    "position": "",
    "number": 89,
    "image": "sticker.png",
},{
    "firstName": "Tobias",
    "lastName": "Pilz",
    "position": "",
    "number": 91,
    "image": "sticker.png",
},{
    "firstName": "Phil",
    "lastName": "Goeters",
    "position": "DT",
    "number": 93,
    "image": "sticker.png",
},{
    "firstName": "Pierre",
    "lastName": "Wachs",
    "position": "DT",
    "number": 94,
    "image": "sticker.png",
},{
    "firstName": "Tobias",
    "lastName": "Walther",
    "position": "DT",
    "number": 97,
    "image": "sticker.png",
},{
    "firstName": "Dominik",
    "lastName": "Werner",
    "position": "DT",
    "number": 99,
    "image": "sticker.png",
},
];